### ISSUE TITLE
Backoffice Search returns no or wrong results

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#11]
When you use the Backoffice Search with the ElasticSearch-provider enabled, the results do not match the searchstring.
For testing i used Paul Seal's Clean Starterkit.

For example, if you search for the page "About" these results are shown:

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/4eed39e9-8107-4219-93ff-8fd5b899d278)

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/ad566a86-0427-480d-95e5-fc034ec01788)

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/7bd452e6-65cb-43cd-80cf-f673edcd29cf)

**Comment by bielu** [comment]
I will have a look this or next weekend

**Comment by mcl-sz** [comment]
I think I have found the source of the problem. It appears that the Analyzers are not being set. The query is lowercased, so that, for example, a node with key "ab...." is found, but the node name with "Ab" is not.

I'll see if I can make an adjustment for this.

**Comment by mcl-sz** [comment]
I have tried to set up the Analyzer but am not getting the desired result yet. I suspect that my knowledge of this is not sufficient unfortunately. Would you like to take a look at this yourself?

What is also noticeable is that the query is also executed on the __Key field.
`+(+(nodeName:a* nodeName_en-us:a* id:a* __NodeId:a* __Key:a*) +__IndexType:content)`

Because this is a Guid it does not contain any relevant data.

**Comment by bielu** [comment]
@mcl-sz this query means:
it has to be, both
- node name or nodename in current culture or id or node id or key
- type: content
so it shouldnt really matter what is in KEY 
but yeah I will play around with on this/next weekend

**Comment by bielu** [comment]
@mcl-sz this one is resolved now, version 1.0.0-beta.638479375162914272 should help you

**Comment by mcl-sz** [comment]
Hi @bielu, the backoffice search works better now, but unfortunately matches based on keys are still found, resulting in irrelevant results. 

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/55d1a928-590a-4763-843e-5aef796f8c3e)

The query `+(+(nodeName:ab^10.0 nodeName_en-us:ab^10.0 nodeName:ab* nodeName_en-us:ab* id:ab* __NodeId:ab* __Key:ab*) +__IndexType:content)`

Gives this result in Kibana:

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/73978fef-7ec0-4dfa-ad0f-fdcb137a33f3)



However, I only now saw that this is exactly the same with Examine Lucene, simply because the __Key is also included in the query there.

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/1c64e503-3e6c-4418-8f7d-3429b3d112dc)


I can imagine that it is useful that you can also search by keys, but it now clouds the results. It might be an idea to check whether a search query is a Guid and that it can then be searched for.  It looks like they were planning something like that in Examine Lucene too, but it wasn't worked out properly; https://github.com/umbraco/Umbraco-CMS/blob/b0016687eb583a549da8992f5fba92e269b4cbfa/src/Umbraco.Examine.Lucene/BackOfficeExamineSearcher.cs#L80

What are your thoughts on this?

**Comment by bielu** [comment]
@mcl-sz I will need investigate it further, but approach of umbraco is not really an good solutions here.

**Comment by mcl-sz** [comment]
I've created an issue under Umbraco-CMS as well because in the base the query sent from Umbraco does not produce the desired result. https://github.com/umbraco/Umbraco-CMS/issues/16003

**Comment by bielu** [comment]
@mcl-sz I am closing this ticket as this has to be fixed in umbraco not provider. :)
