### ISSUE TITLE
Analyzer settings are not (yet) wired up at the moment.

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#15]
It is not yet possible to set up the analyzer. The configuration settings do offer a possibility for this, but it has not yet been implemented.

**Comment by bielu** [comment]
@mcl-sz do you mean examine configuration for index?

**Comment by mcl-sz** [comment]
@bielu, yes, that's what I mean indeed. The `IndexConfiguration` has an Analyzer option but it is not set anywhere (so it's always null). I tried to link this to `ElasticSearchBaseIndex` but it's difficult to do this in a nice way because it's not actually part of IndexState.

**Comment by bielu** [comment]
@mcl-sz I will have a look into it, as we might need inject it into state service

**Comment by bielu** [comment]
Similarly to other ticket changes are on same branch.
btw I didnt use Examine cofiguration I used analyzer field from Bielu Examine provider, let me know if that works for you!

**Comment by mcl-sz** [comment]
@bielu I made a small adjustment and added it to the same pull request as TransformingIndexValues.

**Comment by bielu** [comment]
Hey @mcl-sz I am starting having little more time now again,
Wanted to check if you encounter any other issues on this as will be preparing to release another beta!

**Comment by mcl-sz** [comment]
Hi @bielu , 

Apologies for my late response! I will be doing extensive testing again in the coming days.

One of the things I've run into is that child nodes are not removed from the index when the parent node is removed. Apologies for my late response! I will be doing extensive testing again in the coming days. I'll just create a new issue for this.

**Comment by bielu** [comment]
@mcl-sz I guess we can close this ticket now, if not ping me and will reopen it
