### ISSUE TITLE
Childnodes not deleted from index if parent node is deleted

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#18]
For example, if the "Authors" node contains some child "Author"-nodes and the "Authors" node is deleted, the "Author"-nodes remain in the index.

**Comment by bielu** [comment]
@mcl-sz I will have time post 15th of June, I will have a look than!

**Comment by mcl-sz** [comment]
I've created a pr (https://github.com/bielu/bielu.examine.providers/pull/22) to delete childnodes from the indexes. Could you give it a try?

**Comment by bielu** [comment]
@mcl-sz I guess we can close this ticket now, if not ping me and will reopen it
