### ISSUE TITLE
Trashed nodes remain in the External- and DeliveryApi index

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#19]
When a node is deleted to the trashbin, the node remains in the External- and DeliveryApi index. In the default Lucene-indexes these nodes are deleted from the index  when trashed.

**Comment by mcl-sz** [comment]
In the current latest V13 version of Umbraco (13.3.2) trashed nodes get deleted from the DeliveryApiContentIndex in ElasticSearch. In the ExternalIndex they still remain. I've tried to locate the problem but couldn't find it (yet) for the ExternalIndex.

The problem with the current construction for the DeliveryApiContentIndex is that nodes are removed based on the id field. If you do not use multiple cultures, this works fine (personally I don't use multiple cultures). But if you use multiple cultures in an Umbraco site, a document is created for a node per culture.

Therefore, the LuceneIndex in Umbraco also has a separate PerformDeleteFromIndex (https://github.com/umbraco/Umbraco-CMS/blob/5ae5fe338a96098c8bb3f97cdffb423b5c352e56/src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs#L66) method that determines which culture to delete based on the "__NodeId" field.

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/9657b756-ec0a-4042-bfca-25767c1f10cc)

**Comment by bielu** [comment]
that one is interesting as it happened to me also when using examinex 😂 so yeah another example of handling wrongly indexing as it shouldn't be decided on examine what to delete 😢

**Comment by mcl-sz** [comment]
Hey @bielu, i've found the issue for not removing trashed nodes from the ExternalIndex and created a pr (https://github.com/bielu/bielu.examine.providers/pull/23). Could you give it a try?

**Comment by bielu** [comment]
Thanks for it! I was going to pick up last weekend but my body had different plans so i endup little ill ;) you took some of work from this weekend

**Comment by bielu** [comment]
@mcl-sz I guess we can close this ticket now, if not ping me and will reopen it
