### ISSUE TITLE
Members-index is not populated when indexing or saving a member.

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#20]
The member-index is created but it's not getting populated when reindexing or when creating/updating a member.

**Comment by mcl-sz** [comment]
Changing BieluExamineUmbracoContentIndex to BieluExamineUmbracoMemberIndex (pr https://github.com/bielu/bielu.examine.providers/pull/21) was enough to populate the MemberIndex again.

**Comment by bielu** [comment]
@mcl-sz I guess we can close this ticket now, if not ping me and will reopen it
