### ISSUE TITLE
DeliveryApi: query on parentId splits guid on hyphen

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#28]
Lets say you have this DeliveryApi url: `https://localhost:44331/umbraco/delivery/api/v2/content/?fetch=children:/blog/`

The DeliveryApi finds the node with the path "/blog/" and uses the key of the node (for ex. "31523089-f648-4883-9087-ef9a0b83129f") as parentId to find the children in the DeliveryApiIndex.
The problem is that the key get split on the hypens.

I think the image below explains it best (look at query in the Locals tab):

![afbeelding](https://github.com/user-attachments/assets/6d831c39-1b9f-4c63-bbd1-9aa3404e280e)

In Examine Lucene the query looks like this:

![afbeelding](https://github.com/user-attachments/assets/be90cf01-cd9a-4cfc-9073-a2207c567650)

At first I thought the problem was the SearchOptions. In `ApiContentQueryFactory` it is set to "AllowLeadingWildcard = true".

https://github.com/umbraco/Umbraco-CMS/blob/b14ac811eff85b5b748e3a8bd44b012ad8c9c739/src/Umbraco.Cms.Api.Delivery/Services/QueryBuilders/ApiContentQueryFactory.cs#L21

I made a small modification to CreateQuery where the SearchOptions can also be passed. However, this did not make a difference

```

public IQuery CreateQuery(string name, string? indexAlias, string category, BooleanOperation defaultOperation, Analyzer? luceneAnalyzer, LuceneSearchOptions? searchOptions) =>
    new BieluExamineQuery(name, indexAlias,
        new ElasticSearchQueryParser(LuceneVersion.LUCENE_CURRENT, GetPropertiesNames(name).ToArray(),
          luceneAnalyzer ?? new StandardAnalyzer(LuceneVersion.LUCENE_48)), this, loggerFactory,
        loggerFactory.CreateLogger<BieluExamineQuery>(), category, searchOptions ?? new LuceneSearchOptions(), defaultOperation);
```

```
namespace bielu.Examine.Umbraco.Services.QueryBuilders
{
    internal sealed class ApiContentQueryFactory : IApiContentQueryFactory
    {
        /// <inheritdoc/>
        public IQuery CreateApiContentQuery(IIndex index)
        {
            // Needed for enabling leading wildcards searches
            IBieluExamineSearcher searcher = index.Searcher as IBieluExamineSearcher ?? throw new InvalidOperationException($"Index searcher must be of type {nameof(IBieluExamineSearcher)}.");

            IQuery query = searcher.CreateQuery(
                IndexTypes.Content,
                BooleanOperation.And,
                null,
                new LuceneSearchOptions { AllowLeadingWildcard = true });

            return query;
        }
    }
}
```
`builder.Services.AddSingleton<IApiContentQueryFactory, ApiContentQueryFactory>();`

@bielu do you know a way to prevent the guid being split on the hyphens?

**Comment by bielu** [comment]
@mcl-sz setting up field as keyword would prevent if rom being analyzed and splitted

**Comment by mcl-sz** [comment]
It looks like most fields are setup as keyword because the most fielddefinitions in the fieldcollection  have the type "raw"

![afbeelding](https://github.com/user-attachments/assets/9d31ef7e-4001-46cc-ae4f-68370b73f25b)

I think something is wrong here. I will investigate it.

**Comment by mcl-sz** [comment]
After changing the analyzer to KeywordAnalyzer the value doesn't get split anymore but for some wierd reason it adds the query twice (but hey, it gives results :) )

@bielu do you have any idea why it adds the query twice?

```
    internal sealed class ApiContentQueryFactory : IApiContentQueryFactory
    {
        /// <inheritdoc/>
        public IQuery CreateApiContentQuery(IIndex index)
        {
            // Needed for enabling leading wildcards searches
            IBieluExamineSearcher searcher = index.Searcher as IBieluExamineSearcher ?? throw new InvalidOperationException($"Index searcher must be of type {nameof(IBieluExamineSearcher)}.");

            IQuery query = searcher.CreateQuery(
                IndexTypes.Content,
                BooleanOperation.And,
                new KeywordAnalyzer(),
                new LuceneSearchOptions() { AllowLeadingWildcard = true });

            return query;
        }
    }

```


![afbeelding](https://github.com/user-attachments/assets/5da4e14b-9a3f-4414-a5e1-e880248e0421)

**Comment by bielu** [comment]
Tbh not sure, I am assuming Keyword Analyzer is causing it but yeah more complicated would have to debug it.

**Comment by mcl-sz** [comment]
This turned out to be caused by me adding line 33 regarding debugging :)

I made a PR (https://github.com/bielu/bielu.examine.providers/pull/29), would you mind taking a look? In order to set up the modified Analyzer I had to adjust a number of interfaces.

**Comment by mcl-sz** [comment]
Hey @bielu , thanks for adding the pull request. Now that a lot of the functionality of the package is working, would you like to create a new beta version of the NuGet packages?

**Comment by bielu** [comment]
@mcl-sz I will have a look in weekend into it as something broke pipeline as it should package as soon we merge to main ;)

**Comment by bielu** [comment]
@mcl-sz i released it now as stable version, lets go from there with future fixes and updates. 
closing this ticket as it resolve your issue, let me know if you have any other issues or propositions.
I will try now prepare provider for azure search :)
