### ISSUE TITLE
FieldDefinitionCollection is empty

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#3]
Hi @bielu ,  

While I was testing the beta I noticed that all indexes in the Examine dashboard only contained 4 fields, namely 
`Id, __IndexType, __NodeId, __NodeTypeAlias`

Previously (v8) response.GetMappingFor(indexesMappedToAlias[0]).Properties; returned all fields in the index, but now it is only these 4. The "Runtime" property does contain a list of all fields, but is it wise to use these?

https://github.com/bielu/bielu.examine.providers/blob/83594edf4949c5cce9fe8a069e9bafa159fce7de/src/Bielu.Examine.ElasticSearch/Providers/ElasticsearchExamineSearcher.cs#L92

**Comment by bielu** [comment]
HI @mcl-sz, 
that is deffo bug it should return all properties, I will have a look on the weekend :)

**Comment by bielu** [comment]
My assumption issue is related to new mapping in v8 and docs are not great yet so I was little blind here :) I saw content index and was happy 😂 so might need invesitgate get mapping for!

**Comment by mcl-sz** [comment]
Another point I noticed, and which may also be related to this, is that the ExternalIndex PublishedValuesOnly is set to false.

**Comment by bielu** [comment]
@mcl-sz can you open separate ticket for it so I can track them separatelly, please? :)

**Comment by bielu** [comment]
This is fixed as well, it was related to me wrongly using mapping methods, now it works as should :)

**Comment by mcl-sz** [comment]
This works like a charm!
