### ISSUE TITLE
ExternalIndex PublishedValuesOnly is set to false

### ISSUE THREAD

**Issue by mcl-sz** [bielu/bielu.examine.providers#4]
The ExternalIndex index contains docs that are not published because PublishedValuesOnly is set to false.
For the ExternalIndex PublishedValuesOnly should be true.

![afbeelding](https://github.com/bielu/bielu.examine.providers/assets/18614643/43bdfc5b-e215-4bed-aca3-0ca630c547e4)

**Comment by bielu** [comment]
This one is pretty easy to  resolve issue, so I should be able to resolve it this week, I also started bigger refactor, but it might be too much for weekend to resolve. :) 
issue was related to injecting IndexOptions instead LuceneDirectoryIndexOptions

**Comment by bielu** [comment]
Hey @mcl-sz as mentioned earlier it was issue with using wrong options, as umbraco is overriding them, so it is fixed, can you test this beta
beta.638456899586285693

**Comment by mcl-sz** [comment]
Hey @bielu,
Thank you very much for the great amount of work you put into this project last weekend! I really appreciate this very much! All three points now work fine. Unfortunately I also came across a few new things. Sorry! I will create new issues for it. 

Again, thank you very much!
